name: 'coverage'
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn
        run: yarn
      - name: Run eslint
        run: yarn lint:eslint
      # Skip until the following is corrected.
      # https://github.com/facebookexperimental/Recoil/issues/1902
#       - name: Run type check
#         run: yarn lint:tsc
      - name: Run jest
        run: yarn test
