name: 'release'
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - name: install dependencies
        run: yarn
      - name: release check
        # Skip until the following is corrected.
        # https://github.com/facebookexperimental/Recoil/issues/1902
        # yarn lint
        run: |
          yarn test
          yarn run lint:lib:eslint
      - name: build
        run: yarn build
      - name: npm release
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: gtihub release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            package.json
            yarn.lock
            dist/*
            src/
            tsconfig.json
